# Generated by Django 4.1.4 on 2022-12-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Телефоны',
                'verbose_name_plural': 'Телефоны',
                'ordering': ['-id'],
            },
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['slug'], name='phones_phon_slug_56579b_idx'),
        ),
    ]
