# Generated by Django 4.1.4 on 2022-12-18 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.DateField(null=True, verbose_name='Data relyse'),
        ),
        migrations.AddIndex(
            model_name='phone',
            index=models.Index(fields=['price', 'lte_exists'], name='phones_phon_price_0f4743_idx'),
        ),
    ]
